import { stringify } from "yaml";
import type { CompiledAgent } from "../../builder/types.js";

/**
 * Compile a CompiledAgent into a DeepSeek Harness patch layer.
 *
 * This is what makes `dsh` a different target from `acp` rather than a
 * rename of it. Over plain ACP the agent arrives with whatever tools its
 * deployment mounted — measured against a stock DSH session, forty of them,
 * including a shell (see docs/poc-review-2026-09-02.md §9.4). A Cordis patch
 * is applied before the agent exists, so the tools the manifest does not
 * justify are never mounted at all.
 *
 * Two mechanisms, each used where it was measured to work:
 *
 *   Sandbox mode gates FILE effects and fails closed — a read-only run was
 *   refused a write and could not escalate without an approver (§9.5). So
 *   file tools stay mounted and `DSH_PERMISSION_MODE` decides what they may
 *   do.
 *
 *   Sandbox mode does NOT gate exec or network: under `read-only`, bash still
 *   ran `curl` and got HTTP 200 (§9.5). A shell therefore cannot be gated
 *   after the fact, so it is withheld by composition unless the manifest
 *   grants irreversible effects.
 */

/** Cordis row ids in `@deepseek-ai/dsh-base`, by what mounting them permits. */
const SHELL_TOOLS = ["tool-bash", "tool-pwsh"];

/**
 * Tools that let an agent start more agents or drive its own loops. None of
 * them is expressible in the manifest yet (sub-agents are P5), and an agent
 * that can spawn another one escapes whatever tool set this patch just chose.
 *
 * These are Cordis ROW ids, not package names, and the base bundle mounts one
 * package under several rows: `dsh-tool-subagent` appears as both
 * `tool-subagent` and `tool-subagent-fork`, each configured with a different
 * `toolName`. Disabling by package name would have left `subagent_fork`
 * mounted — which it did, until a run against the real harness showed the
 * tool still in the agent's own list.
 */
const DELEGATION_TOOLS = [
  "tool-subagent",
  "tool-subagent-fork",
  "tool-subagent-control",
  "tool-subagent-list-agents",
  "tool-ralph",
  "tool-workflow",
];

/**
 * Web access. `web_search` and `web_fetch` only read, so they belong to an
 * agent that may read — but a fetched URL is also a way to send data out, and
 * at autonomy 0 nothing is supposed to happen without a human. The harness
 * will not ask us about a network call, so the only way to hold that line is
 * not to mount the tools.
 */
const WEB_TOOLS = ["tool-web"];

export type PermissionMode = "read-only" | "workspace-write" | "danger-full-access";

export interface DshPreset {
  /** YAML for `--patch`. */
  patch: string;
  /** Value for DSH_PERMISSION_MODE in the agent's environment. */
  permissionMode: PermissionMode;
  /** Row ids this patch switches off, for the trace and for tests. */
  withheld: string[];
}

/**
 * `spec.autonomy.level` -> how much the sandbox lets through.
 *
 * Level 3 is the only one that maps to `danger-full-access`, which also turns
 * the approval policy to `never` in the shipped base bundle — correct for an
 * agent the manifest says may act without asking, and wrong for any other.
 */
function permissionModeFor(level: number): PermissionMode {
  if (level >= 3) return "danger-full-access";
  if (level === 2) return "workspace-write";
  return "read-only";
}

export function buildPreset(compiled: CompiledAgent): DshPreset {
  const mayAct = compiled.autonomy.allowedEffects.includes("irreversible");
  const mayRead = compiled.autonomy.allowedEffects.includes("read");
  const withheld = [
    ...DELEGATION_TOOLS,
    ...(mayAct ? [] : SHELL_TOOLS),
    ...(mayRead ? [] : WEB_TOOLS),
  ];

  const rows: unknown[] = [
    {
      // The manifest owns who the agent is. It deliberately does not set
      // `complete: true`: the runtime still gets to explain its own tools,
      // which is knowledge the manifest does not have and should not carry.
      id: "system-prompt",
      config: { persona: compiled.systemPrompt },
    },
    {
      id: "llm-pi-ai",
      config: {
        providers: {
          "agent-builder": {
            displayName: "Agent Builder",
            apiKeyEnv: compiled.model.apiKeyEnv,
            baseURL: compiled.model.baseUrl,
            api: "openai-completions",
            models: [{ id: compiled.model.id, name: compiled.model.id, contextWindow: 200000 }],
          },
        },
      },
    },
    {
      id: "acp",
      config: { provider: "agent-builder", model: compiled.model.id },
    },
    ...withheld.map((id) => ({ id, disabled: true })),
  ];

  const header = [
    "# Generated by agent-builder — do not edit.",
    `# agent:    ${compiled.name}@${compiled.version}`,
    `# manifest: ${compiled.manifestChecksum}`,
    `# autonomy: level ${compiled.autonomy.level} (${compiled.autonomy.allowedEffects.join(", ") || "nothing"})`,
    "",
  ].join("\n");

  return { patch: header + stringify(rows), permissionMode: permissionModeFor(compiled.autonomy.level), withheld };
}
